package com.eames.taekwondo.handlers;

/**
 * This class encapsulates the internal responses generated by the intents.
 */
public class IntentResponse {

    /*
     * The speech text.
     */
    final private String speechText;

    /*
     * The 'needs response' flag.
     */
    final private boolean needsResponse;

    /**
     * Constructor
     *
     * @param speechText the speech text
     * @param needsResponse the 'needs response' flag
     */
    public IntentResponse(String speechText, boolean needsResponse) {
        this.speechText = speechText;
        this.needsResponse = needsResponse;
    }

    public String getSpeechText() {
        return speechText;
    }

    public boolean isNeedsResponse() {
        return needsResponse;
    }
}
